export default Images = {
  logo: require('../../assets/images/logo.png'),
  audition: require('../../assets/images/audition.png'),
  cardBlue: require('../../assets/images/card-bg-blue.png'),
  cardBlue2: require('../../assets/images/card-bg-blue-2.png'),
  coin: require('../../assets/images/coin.png'),
  eShowcase: require('../../assets/images/e-showcase.png'),
  greetings: require('../../assets/images/greetings.png'),
  learningSession: require('../../assets/images/learning-session.png'),
  liveChat: require('../../assets/images/live-chat.png'),
  meetUp: require('../../assets/images/meet-up.png'),
  paidPost: require('../../assets/images/paid-post.png'),
  qA: require('../../assets/images/q&a.png'),
  profile1: require('../../assets/images/profile_1.png'),
  setting: require('../../assets/images/settings.png'),
  notification: require('../../assets/images/notification.png'),
  placeholderImg: require('../../assets/images/placeholder-image.png'),
};
