export default RouteName = {
  home: 'Home',
  signUp: 'SignUp',
  signIn: 'SignIn',
  bottomTab: 'BottomTab',
  notification: 'Notification',
  menu: 'Menu',
  greetings: 'Greetings',
  allGreetings: 'AllGreetings',
  createGreetings: 'CreateGreetings',
  detailsGreetings: 'GreetingDetails',
  video: 'VideoScreen',
  cropper: 'VideoCropperScreen',
  greetingForm: 'GreetingForm',
  fileUpload: 'FileUpload',
  fileList: 'FileList',
  videoUpload: 'VideoUpload',
  uploadList: 'uploadList',
  backgroundUpload: 'BackgroundUpload',
};
